### ISSUE TITLE
Unittests

### ISSUE THREAD

**Issue by Kamori** [ABORGT/PylertAlertManager#3]
doctest seems like an easy answer here.

We can use that to generate both sphynx docs and tests our code automagically

**Comment by Kamori** [comment]
https://github.com/patrys/httmock

Should we use
doctest
nose2
unittests ??

**Comment by jpavlav** [comment]
I like the idea of using doctest, mainly because it's usage is a good enforcer for having good doc strings :). Having said that, implementation might get a little more complicated than I want with doctest. I've never used nose2, but reading about it, it too seems like a good solution. I'd say, let's go with nose2, if not nose2, doctest.

**Comment by jpavlav** [comment]
Working on this actively. Considering what we are testing and my familiarity with discussed tools, I'm going to go with straight python unittests. If we want to change this in the future we certainly can.

**Comment by jpavlav** [comment]
We should be able to close this one once this merge is complete:

https://github.com/ABORGT/PylertAlertManager/pull/20
